-- Reclassify existing seeded exercises into the new granular categories,
-- then add the expanded exercise library across all muscle groups.

update public.exercises set category = 'triceps' where name = 'Cable Tricep Pushdown';
update public.exercises set category = 'biceps' where name = 'Dumbbell Bicep Curl';
update public.exercises set category = 'quads' where name in (
  'Barbell Back Squat', 'Bulgarian Split Squat', 'Dumbbell Lunge',
  'Front Squat', 'Goblet Squat', 'Leg Extension', 'Leg Press'
);
update public.exercises set category = 'hamstrings' where name in ('Leg Curl', 'Romanian Deadlift');

insert into public.exercises (name, category, equipment) values
  -- Chest
  ('Decline Bench Press', 'chest', 'barbell'),
  ('Incline Dumbbell Press', 'chest', 'dumbbell'),
  ('Decline Dumbbell Press', 'chest', 'dumbbell'),
  ('Smith Machine Bench Press', 'chest', 'machine'),
  ('Floor Press', 'chest', 'barbell'),
  ('Dumbbell Fly', 'chest', 'dumbbell'),
  ('Incline Fly', 'chest', 'dumbbell'),
  ('Decline Fly', 'chest', 'dumbbell'),
  ('Cable Fly (High-to-Low)', 'chest', 'cable'),
  ('Cable Fly (Low-to-High)', 'chest', 'cable'),
  ('Pec Deck', 'chest', 'machine'),
  ('Chest Press Machine', 'chest', 'machine'),
  ('Incline Push-Up', 'chest', 'bodyweight'),
  ('Decline Push-Up', 'chest', 'bodyweight'),
  ('Diamond Push-Up', 'chest', 'bodyweight'),
  ('Archer Push-Up', 'chest', 'bodyweight'),
  ('Ring Push-Up', 'chest', 'bodyweight'),
  ('Plyometric Push-Up', 'chest', 'bodyweight'),
  ('Svend Press', 'chest', 'other'),

  -- Back
  ('Rack Pull', 'back', 'barbell'),
  ('T-Bar Row', 'back', 'machine'),
  ('Bent-Over Barbell Row', 'back', 'barbell'),
  ('Pendlay Row', 'back', 'barbell'),
  ('Seal Row', 'back', 'barbell'),
  ('Meadows Row', 'back', 'barbell'),
  ('Chest-Supported Row', 'back', 'machine'),
  ('Seated Cable Row', 'back', 'cable'),
  ('Machine Row', 'back', 'machine'),
  ('Wide-Grip Row', 'back', 'cable'),
  ('Close-Grip Row', 'back', 'cable'),
  ('Inverted Row', 'back', 'bodyweight'),
  ('Chin-Up', 'back', 'bodyweight'),
  ('Neutral Grip Pull-Up', 'back', 'bodyweight'),
  ('Weighted Pull-Up', 'back', 'bodyweight'),
  ('Straight Arm Pulldown', 'back', 'cable'),
  ('Machine Pullover', 'back', 'machine'),
  ('Dumbbell Pullover', 'back', 'dumbbell'),
  ('Shrug', 'back', 'barbell'),
  ('Farmer Carry', 'back', 'dumbbell'),

  -- Shoulders
  ('Seated Dumbbell Press', 'shoulders', 'dumbbell'),
  ('Arnold Press', 'shoulders', 'dumbbell'),
  ('Push Press', 'shoulders', 'barbell'),
  ('Machine Shoulder Press', 'shoulders', 'machine'),
  ('Landmine Press', 'shoulders', 'barbell'),
  ('Front Raise', 'shoulders', 'dumbbell'),
  ('Cable Lateral Raise', 'shoulders', 'cable'),
  ('Leaning Lateral Raise', 'shoulders', 'cable'),
  ('Rear Delt Fly', 'shoulders', 'dumbbell'),
  ('Reverse Pec Deck', 'shoulders', 'machine'),
  ('Face Pull', 'shoulders', 'cable'),
  ('Upright Row', 'shoulders', 'barbell'),
  ('Cuban Press', 'shoulders', 'dumbbell'),
  ('Y Raise', 'shoulders', 'dumbbell'),
  ('Trap-3 Raise', 'shoulders', 'dumbbell'),

  -- Biceps
  ('Barbell Curl', 'biceps', 'barbell'),
  ('EZ Bar Curl', 'biceps', 'barbell'),
  ('Alternating Curl', 'biceps', 'dumbbell'),
  ('Hammer Curl', 'biceps', 'dumbbell'),
  ('Cross Body Hammer Curl', 'biceps', 'dumbbell'),
  ('Incline Curl', 'biceps', 'dumbbell'),
  ('Concentration Curl', 'biceps', 'dumbbell'),
  ('Preacher Curl', 'biceps', 'barbell'),
  ('Machine Preacher Curl', 'biceps', 'machine'),
  ('Spider Curl', 'biceps', 'barbell'),
  ('Bayesian Curl', 'biceps', 'cable'),
  ('Cable Curl', 'biceps', 'cable'),
  ('Reverse Curl', 'biceps', 'barbell'),
  ('Zottman Curl', 'biceps', 'dumbbell'),
  ('Drag Curl', 'biceps', 'barbell'),
  ('High Cable Curl', 'biceps', 'cable'),

  -- Triceps
  ('Rope Pushdown', 'triceps', 'cable'),
  ('Straight Bar Pushdown', 'triceps', 'cable'),
  ('Single Arm Pushdown', 'triceps', 'cable'),
  ('Overhead Cable Extension', 'triceps', 'cable'),
  ('Overhead Dumbbell Extension', 'triceps', 'dumbbell'),
  ('Skull Crusher', 'triceps', 'barbell'),
  ('JM Press', 'triceps', 'barbell'),
  ('Close-Grip Bench Press', 'triceps', 'barbell'),
  ('Bench Dips', 'triceps', 'bodyweight'),
  ('Kickback', 'triceps', 'dumbbell'),
  ('Tate Press', 'triceps', 'dumbbell'),
  ('PJR Pullover', 'triceps', 'barbell'),

  -- Quads
  ('Hack Squat', 'quads', 'machine'),
  ('Smith Squat', 'quads', 'machine'),
  ('Belt Squat', 'quads', 'machine'),
  ('Walking Lunge', 'quads', 'dumbbell'),
  ('Reverse Lunge', 'quads', 'dumbbell'),
  ('Step-Up', 'quads', 'dumbbell'),
  ('Sissy Squat', 'quads', 'bodyweight'),
  ('Wall Sit', 'quads', 'bodyweight'),

  -- Hamstrings
  ('Stiff Leg Deadlift', 'hamstrings', 'barbell'),
  ('Good Morning', 'hamstrings', 'barbell'),
  ('Nordic Curl', 'hamstrings', 'bodyweight'),
  ('Lying Leg Curl', 'hamstrings', 'machine'),
  ('Seated Leg Curl', 'hamstrings', 'machine'),
  ('Glute Ham Raise', 'hamstrings', 'machine'),
  ('Single Leg RDL', 'hamstrings', 'dumbbell'),
  ('Cable Pull Through', 'hamstrings', 'cable'),

  -- Glutes
  ('Hip Thrust', 'glutes', 'barbell'),
  ('Glute Bridge', 'glutes', 'bodyweight'),
  ('Frog Pump', 'glutes', 'bodyweight'),
  ('Cable Kickback', 'glutes', 'cable'),
  ('Reverse Hyper', 'glutes', 'machine'),
  ('Curtsy Lunge', 'glutes', 'dumbbell'),
  ('Sumo Deadlift', 'glutes', 'barbell'),

  -- Calves
  ('Standing Calf Raise', 'calves', 'machine'),
  ('Seated Calf Raise', 'calves', 'machine'),
  ('Donkey Calf Raise', 'calves', 'machine'),
  ('Single Leg Calf Raise', 'calves', 'bodyweight'),
  ('Leg Press Calf Raise', 'calves', 'machine'),
  ('Tibialis Raise', 'calves', 'other'),

  -- Abs & Core
  ('Crunch', 'core', 'bodyweight'),
  ('Sit-Up', 'core', 'bodyweight'),
  ('Bicycle Crunch', 'core', 'bodyweight'),
  ('Reverse Crunch', 'core', 'bodyweight'),
  ('Hanging Knee Raise', 'core', 'bodyweight'),
  ('Toes to Bar', 'core', 'bodyweight'),
  ('Ab Wheel Rollout', 'core', 'other'),
  ('Cable Crunch', 'core', 'cable'),
  ('Russian Twist', 'core', 'bodyweight'),
  ('Side Plank', 'core', 'bodyweight'),
  ('Hollow Hold', 'core', 'bodyweight'),
  ('Dead Bug', 'core', 'bodyweight'),
  ('Bird Dog', 'core', 'bodyweight'),
  ('Mountain Climbers', 'core', 'bodyweight'),
  ('V-Up', 'core', 'bodyweight'),
  ('Dragon Flag', 'core', 'bodyweight'),
  ('Pallof Press', 'core', 'cable'),
  ('Woodchopper', 'core', 'cable'),

  -- Forearms & Grip
  ('Wrist Curl', 'forearms', 'dumbbell'),
  ('Reverse Wrist Curl', 'forearms', 'dumbbell'),
  ('Wrist Roller', 'forearms', 'other'),
  ('Plate Pinch', 'forearms', 'other'),
  ('Dead Hang', 'forearms', 'bodyweight'),
  ('Towel Pull-Up', 'forearms', 'bodyweight'),
  ('Fat Grip Curl', 'forearms', 'dumbbell'),
  ('Finger Curl', 'forearms', 'dumbbell'),
  ('Gripper Squeeze', 'forearms', 'other'),

  -- Olympic Lifts
  ('Clean', 'olympic', 'barbell'),
  ('Hang Clean', 'olympic', 'barbell'),
  ('Power Clean', 'olympic', 'barbell'),
  ('Clean and Jerk', 'olympic', 'barbell'),
  ('Snatch', 'olympic', 'barbell'),
  ('Hang Snatch', 'olympic', 'barbell'),
  ('Push Jerk', 'olympic', 'barbell'),
  ('Split Jerk', 'olympic', 'barbell'),
  ('High Pull', 'olympic', 'barbell'),

  -- Full Body
  ('Thruster', 'full_body', 'barbell'),
  ('Burpee', 'full_body', 'bodyweight'),
  ('Turkish Get-Up', 'full_body', 'kettlebell'),
  ('Man Maker', 'full_body', 'dumbbell'),
  ('Devil Press', 'full_body', 'dumbbell'),
  ('Sandbag Clean', 'full_body', 'sandbag'),
  ('Sled Push', 'full_body', 'sled'),
  ('Sled Pull', 'full_body', 'sled'),
  ('Battle Ropes', 'full_body', 'other'),
  ('Tire Flip', 'full_body', 'other'),
  ('Rope Climb', 'full_body', 'bodyweight'),

  -- Cardio
  ('Running', 'cardio', 'other'),
  ('Walking', 'cardio', 'other'),
  ('Sprinting', 'cardio', 'other'),
  ('Cycling', 'cardio', 'other'),
  ('Rowing', 'cardio', 'machine'),
  ('Swimming', 'cardio', 'other'),
  ('Stair Climber', 'cardio', 'machine'),
  ('Elliptical', 'cardio', 'machine'),
  ('Jump Rope', 'cardio', 'other'),
  ('Ski Erg', 'cardio', 'machine'),
  ('Air Bike', 'cardio', 'machine'),
  ('Hiking', 'cardio', 'other'),

  -- Functional & Athletic
  ('Box Jump', 'full_body', 'bodyweight'),
  ('Broad Jump', 'full_body', 'bodyweight'),
  ('Depth Jump', 'full_body', 'bodyweight'),
  ('Lateral Bounds', 'full_body', 'bodyweight'),
  ('Medicine Ball Slam', 'full_body', 'medicine_ball'),
  ('Rotational Throw', 'full_body', 'medicine_ball'),
  ('Agility Ladder', 'full_body', 'other'),
  ('Cone Drills', 'full_body', 'other'),
  ('Sled Sprint', 'full_body', 'sled'),
  ('Bear Crawl', 'full_body', 'bodyweight'),
  ('Crab Walk', 'full_body', 'bodyweight'),
  ('Shuttle Run', 'full_body', 'other'),
  ('Prowler Push', 'full_body', 'sled'),

  -- Mobility & Stretching
  ('World''s Greatest Stretch', 'mobility', 'bodyweight'),
  ('Hip Flexor Stretch', 'mobility', 'bodyweight'),
  ('Couch Stretch', 'mobility', 'bodyweight'),
  ('Hamstring Stretch', 'mobility', 'bodyweight'),
  ('Quad Stretch', 'mobility', 'bodyweight'),
  ('Calf Stretch', 'mobility', 'bodyweight'),
  ('Child''s Pose', 'mobility', 'bodyweight'),
  ('Cat-Cow', 'mobility', 'bodyweight'),
  ('Thoracic Rotation', 'mobility', 'bodyweight'),
  ('Shoulder Dislocates', 'mobility', 'band'),
  ('Band Pull Apart', 'mobility', 'band'),
  ('Foam Rolling', 'mobility', 'other');
